# contexto.py

def get_contexto_ecossistema_inovacao():
    return (
        "Ecossistemas de inovação são ambientes colaborativos que reúnem "
        "empresas, universidades, centros de pesquisa, startups, governo e "
        "sociedade com o objetivo de promover a inovação, o empreendedorismo "
        "e o desenvolvimento tecnológico.\n"
        "Esses ecossistemas se caracterizam pela interação e sinergia entre "
        "diferentes atores, facilitando a troca de conhecimento, a co-criação "
        "e o desenvolvimento de soluções inovadoras para desafios locais e "
        "globais.\n"
        "No Brasil, políticas públicas, incentivos, redes de apoio, "
        "incubadoras, aceleradoras, investidores e eventos de inovação são "
        "elementos fundamentais para fortalecer esses ambientes.\n"
        "A atuação integrada dos participantes permite a geração de valor, o "
        "crescimento econômico, o impacto social e a adaptação às demandas do "
        "mercado e da sociedade.\n"
        "Ecossistemas de inovação são dinâmicos e evoluem conforme as "
        "necessidades e oportunidades, sendo essenciais para a competitividade "
        "e sustentabilidade das regiões onde estão inseridos."
    )

def get_contexto_parque_tecnologico_santos():
    return (
        "O Parque Tecnológico de Santos é uma autarquia localizado na região "
        "de Santos, que integra empresas, universidades, centros de pesquisa "
        "e startups com o propósito de impulsionar o desenvolvimento "
        "tecnológico, a inovação e o empreendedorismo.\n"
        "O parque oferece programas de incubação, aceleração, capacitação, "
        "eventos e projetos colaborativos, estimulando a geração de "
        "conhecimento, soluções inovadoras e impacto socioeconômico.\n"
        "Atua como elo entre academia, setor produtivo e governo, promovendo "
        "a competitividade e o crescimento sustentável.\n"
        "O Parque Tecnológico de Santos é parte fundamental do ecossistema de "
        "inovação local, apoiando iniciativas que visam transformar ideias em "
        "negócios e fortalecer a economia regional por meio da inovação."
    )


def get_contexto_exemplos_ecossistemas_inovacao():
    return (
        "1. Cubo Itaú (São Paulo):\n"
        "O Cubo Itaú é um dos maiores hubs de inovação da América Latina, "
        "localizado em São Paulo. Fundado em 2015 pelo Itaú Unibanco em "
        "parceria com a Redpoint eventures, o Cubo reúne startups, grandes "
        "empresas, investidores, universidades e especialistas em tecnologia. "
        "O espaço físico e digital do Cubo promove eventos, programas de "
        "aceleração, mentorias e networking, facilitando a conexão entre "
        "diferentes atores do ecossistema. O Cubo é reconhecido por "
        "impulsionar o crescimento de startups, fomentar a cultura de "
        "inovação corporativa e criar oportunidades de negócios disruptivos. "
        "Sua atuação é marcada pela diversidade de setores, desde fintechs "
        "até healthtechs, e pelo engajamento ativo com o mercado nacional e "
        "internacional.\n\n"
        "2. Parque Tecnológico de São José dos Campos:\n"
        "Este parque é referência nacional em inovação, ciência e tecnologia, "
        "especialmente nos setores aeroespacial, defesa, energia e TI. O "
        "Parque Tecnológico de São José dos Campos abriga empresas de todos "
        "os portes, centros de pesquisa, laboratórios, incubadoras e "
        "aceleradoras. Sua estrutura oferece suporte para desenvolvimento de "
        "projetos, transferência de tecnologia, capacitação e "
        "internacionalização de negócios. O parque atua como elo entre "
        "academia, indústria e governo, promovendo parcerias estratégicas e "
        "projetos colaborativos que geram impacto regional e nacional. "
        "Destaca-se pela integração com o setor produtivo e pela geração de "
        "empregos qualificados.\n\n"
        "3. Porto Digital (Recife):\n"
        "Localizado no Recife, Porto Digital é um dos maiores parques "
        "tecnológicos e ambientes de inovação do Brasil, com foco em "
        "tecnologia da informação, comunicação e economia criativa. Fundado "
        "em 2000, o Porto Digital transformou a região histórica do Recife "
        "Antigo em um polo de inovação, reunindo mais de 350 empresas, "
        "startups, instituições de ensino e pesquisa. O ecossistema oferece "
        "infraestrutura, programas de capacitação, eventos, incentivos "
        "fiscais e apoio à internacionalização. Porto Digital é reconhecido "
        "por sua contribuição ao desenvolvimento econômico de Pernambuco, "
        "geração de empregos e exportação de tecnologia. O ambiente estimula "
        "a colaboração entre empresas, governo e academia, consolidando-se "
        "como referência internacional.\n\n"
        "4. Tecnopuc (Porto Alegre):\n"
        "O Parque Científico e Tecnológico da PUCRS (Tecnopuc) é um "
        "ecossistema de inovação que integra empresas, startups, centros de "
        "pesquisa e laboratórios em Porto Alegre. O Tecnopuc oferece "
        "infraestrutura moderna, programas de incubação, aceleração, "
        "inovação aberta e parcerias internacionais. O parque é reconhecido "
        "pela forte ligação com a universidade, promovendo transferência de "
        "conhecimento e desenvolvimento de soluções inovadoras em áreas como "
        "TI, saúde, energia e educação. O ambiente estimula a formação de "
        "talentos, a pesquisa aplicada e a criação de negócios de alto "
        "impacto, sendo um dos principais polos de inovação do sul do "
        "Brasil.\n\n"
        "5. Parque Tecnológico de Santos:\n"
        "O Parque Tecnológico de Santos é um exemplo de ecossistema de "
        "inovação regional, integrando empresas, universidades, centros de "
        "pesquisa e startups na Baixada Santista. O parque oferece programas "
        "de incubação, aceleração, capacitação, eventos e projetos "
        "colaborativos, estimulando a geração de conhecimento e soluções "
        "inovadoras. Atua como elo entre academia, setor produtivo e "
        "governo, promovendo a competitividade e o crescimento sustentável. "
        "O Parque Tecnológico de Santos é fundamental para o desenvolvimento "
        "econômico local, apoiando iniciativas que transformam ideias em "
        "negócios e fortalecem a economia regional por meio da inovação.\n\n"
        "Esses exemplos ilustram como ecossistemas de inovação podem assumir "
        "diferentes formatos e estratégias, mas compartilham o objetivo de "
    )

def get_contexto_dados_ecossistemas_brasil():
    return (
        "Dados sobre Ecossistemas de Inovação no Brasil:\n\n"
        "O Brasil possui mais de 40 parques tecnológicos em operação e outros "
        "30 em fase de implantação, distribuídos por todas as regiões do país. "
        "Esses ambientes abrigam aproximadamente 2.500 empresas de base "
        "tecnológica e geram mais de 180.000 empregos diretos e indiretos.\n\n"
        "Região Sudeste concentra 45% dos parques tecnológicos brasileiros, "
        "seguida pela região Sul com 28%, Nordeste com 15%, Centro-Oeste com "
        "8% e Norte com 4%. São Paulo lidera com 18 parques, seguido por "
        "Minas Gerais com 8 e Rio Grande do Sul com 7.\n\n"
        "Setores de maior concentração nos ecossistemas brasileiros: TI e "
        "Software (35%), Biotecnologia e Saúde (18%), Energia e "
        "Sustentabilidade (15%), Aeroespacial e Defesa (12%), Agricultura e "
        "Agronegócios (10%), outros setores (10%).\n\n"
        "Investimentos em P&D: O Brasil investe aproximadamente 1,3% do PIB "
        "em pesquisa e desenvolvimento, sendo que 55% provêm do governo e 45% "
        "do setor privado. Os parques tecnológicos recebem anualmente cerca "
        "de R$ 2,8 bilhões em investimentos públicos e privados.\n\n"
        "Startups e Empreendedorismo: Existem mais de 13.000 startups "
        "registradas no país, com crescimento anual de 25%. As aceleradoras "
        "brasileiras já apoiaram mais de 3.500 empresas nascentes, gerando "
        "um ecossistema de inovação com faturamento conjunto superior a "
        "R$ 50 bilhões anuais.\n\n"
        "Universidades e Centros de Pesquisa: O país conta com 195 "
        "universidades públicas e mais de 2.000 instituições de ensino "
        "superior privadas envolvidas em atividades de inovação. Há 63 "
        "Núcleos de Inovação Tecnológica (NITs) ativos, responsáveis pela "
        "transferência de tecnologia universidade-empresa.\n\n"
        "Políticas de Apoio: Lei de Inovação (2004), Lei do Bem (2005), "
        "Marco Legal da Ciência, Tecnologia e Inovação (2016), e Nova Lei "
        "de Licitações (2021) são os principais instrumentos legais de "
        "fomento à inovação. O país destina anualmente R$ 12 bilhões em "
        "recursos públicos para CT&I através de agências como CNPq, CAPES, "
        "FINEP e FAPESP."
    )

def get_contexto():
    """ Função que retorna o contexto completo sobre ecossistemas de inovação no Brasil """
    contexto_completo = (
        get_contexto_ecossistema_inovacao() + "\n\n" +
        get_contexto_parque_tecnologico_santos() + "\n\n" +
        get_contexto_exemplos_ecossistemas_inovacao() + "\n\n" +
        get_contexto_dados_ecossistemas_brasil()
    )
    return contexto_completo
